[build-system]
requires = ["setuptools>=65.0"]
build-backend = "setuptools.build_meta"

[project]
name = "formseal-embed"
version = "3.10.1"
description = "Client-side form encryption that encrypts submissions before they leave the browser and works with any POST endpoint."
readme = "README.md"
license = {file = "LICENSE"}
requires-python = ">=3.8"
dependencies = ["pynacl"]
authors = [
    {name = "grayguava"}
]

[project.urls]
Homepage = "https://github.com/useFormseal/embed"
Repository = "https://github.com/useFormseal/embed.git"

[project.scripts]
fse = "fse.cli:main"

[tool.setuptools]
packages = [
    "fse",
    "fse.commands",
    "fse.helpers",
    "fse.ui",
]

[tool.setuptools.package-data]
fse = ["src/**"]